name: Deploy to EB

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install docker-compose

      - name: Start Docker containers
        run: docker-compose up -d --build

      - name: Run pytest from inside the Flask container
        run: |
          docker exec flask-backend bash -c "python -m pytest"

      - name: Stop Docker containers
        run: docker-compose down -v

      - name: Generate deployment package
        run: |
          cd flask
          zip -r ../deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: medium-app
          environment_name: medium-flask
          version_label: ${{ github.sha }}
          region: eu-north-1
          deployment_package: deploy.zip
